#------ Change this to your needs -----
server='10.0.0.1'
serviceaccount='service'
password='service'
service_id='webservers'
comment='privacyIDEA autocreated'
sshuser='root'
hostname=`hostname`
#insecure=""
insecure="-k"
#--------------------------------------
