#
# Configuration for pep8speaks.
#
# This configures the automatic style checking for pull requests with Python code. Is is intentionally set to be rather
# lax in some areas, to allow developers to make conscious decisions about how to best format to be as readable as
# possible.
#

scanner:
    diff_only: True  # Do not scan the entire file touched by the Pull Request for errors.
    linter: pycodestyle

pycodestyle:
    max-line-length: 100
    exclude: []
    count: False
    first: False
    show-pep8: False
    show-source: False
    statistics: False
    hang-closing: True
    select: []

no_blank_comment: True  # No comment is made on PR without any errors.
descending_issues_order: False  # PEP 8 issues in message will be displayed in ascending order of line numbers per file.
only_mention_files_with_errors: True  # No separate status section for each file is made in the comment.

